title: Michael Solomentsev
description: Electrical engineering student; Maker; Arizonian; Passionate about renewable energy and the positive impact of engineering
logo: /img/me_pink.png
show_downloads: false
theme: jekyll-theme-minimal